### ISSUE TITLE
Houston... you know what comes next

### ISSUE THREAD

**Issue by cyr-l** [trusktr/rocket-module#4]
Hello Mr. trusktr,

I know, I know, I read the memo: it's not v1.0 yet but so few ticks left! :)

I'm trying to use an [npm package](https://github.com/cbioley/react-mdl/tree/textfield) in my Meteor project for a few hours now. The React components are exposed through the ES6 module syntax and I was not able to transform the code via the `cosmos:browserify` (grrrr!)

Since I want to move forward (read: copying the components right into the Meteor app), I now have an issue with the imports.

In my quest, I read like 3 times a reference to this repo. I had to try! :)

Unfortunately I have an error in a pristine Meteor project. Meteor crashes with the message `--- dependents: []rocket:module` from p...  `.

Would you be kind enough to give me some help?

**Comment by trusktr** [comment]
Hello @cbioley, Sorry for the super delayed reply! I missed the email notification somehow. 

Rocket:module totally wasn't ready when you tried it. But, good news: it's almost ready! It's been completely re-written since when you tried it, to take advantage of Meteor 1.2's new Plugin.registerCompiler API. I might put out the first release this weekend, with some initial documentation on how to actually use it. :smile: 

Coincidentally, the first thing I want to do after releasing the first release of rocket:module is use it to import React, [react-famous](https://github.com/pilwon/react-famous), and [Famous Engine](https://github.com/Famous/engine) into one of my projects. So, if you still need help with this, stay tuned. :smiley:

**Comment by cyr-l** [comment]
No worries mate!

Oh yes, I'll stay tuned ^^

Really impressed by all the work you're doing.
