### ISSUE TITLE
Example usage.

### ISSUE THREAD

**Issue by jantimon** [trusktr/rocket-module#5]
Hey is there any example repo which shows the usage of meteor-rocket?

**Comment by cyr-l** [comment]
Not sure we - the mortals - are supposed to use it before v1 (cf. README)

**Comment by jantimon** [comment]
Would just like to see how you would use this plugin and how fast it compiles code.

**Comment by trusktr** [comment]
I'll be putting out the first release this weekend hopefully, along with documentation in the README. I described a possible usage a while back [in the forums](https://forums.meteor.com/t/new-package-rocket-module-to-provide-cjs-amd-es6-modules-for-meteor-packages-with-shared-npm-dependencies/4620/4?u=joe). The usage will be similar, except to define npm dependencies you just use the normal `Npm.depends()` as usual, but `rocket:module` reads the versions you specify there as `^x.x.x` versions instead of absolute versions (this is what makes code-splitting across packages an ideal thing).

I'll definitely put up an example repo for first release. Stay tuned. (:

Oh, and as far as speed goes, it'll be at the speed of Webpack with caching enabled (`rocket:module` is using Webpack behind the scenes).

**Comment by trusktr** [comment]
The example repo will be [here](https://github.com/meteor-rocket/module-example-app), but it's not ready (I haven't initialized the necessary submodules yet and other things). Aiming hard for this weekend.

**Comment by trusktr** [comment]
@cbioley @jantimon Alright guys, the first usable version is out, [v0.2.0](https://github.com/meteor-rocket/module/tree/v0.2.0)! It works, but still needs some important things (listed in the todos): caching so only modified files are rebuilt, source maps, and we've gotta find a fix/workaround for https://github.com/webpack/webpack/issues/1296, testing in windows, common loaders, cross-package imports/exports (planned), etc.

Atmosphere doesn't support the new Plugin.registerCompiler API (it's in the devel branch, so soon!). For now you'll have to clone `rocket:module` into `packages/module` of your app.

`rocket:module` only works with the `devel` branch of Meteor currently. To use the `devel` branch of Meteor in your app, just clone meteor/meteor from GitHub, then before running the `meteor` command run

``` sh
export PATH=/path/to/meteor-repository:$PATH
```

That'll give you the `devel` version of the `meteor` command. Once the `Plugin.registerCompiler` API from the `devel` branch is merged to master (I think that'll be Meteor 1.2?) then you can use the normal `meteor` command, at which point I'll have `rocket:module` on Atmosphere so you won't have to clone `rocket:module` into your app either.

### Basic usage:

**For packages:**
- Make sure your package `api.use`s `rocket:module@0.2.0`
- Declare things in `package.js` just like normal, including npm dependencies with `Npm.depends`.
- Use `api.addFiles` to add files that end with `module.js`. The 'module.js' files are entry points and don't export anything, they only import things. They can export things like normal Meteor packages do, by not using `var`/`let`/etc in the variable definition the using api.export to register the export.
- Add other files (js for now, css, cs, etc coming next). These files (for now) won't get into your app unless you require them from a module.js file, require them from a file required from a module.js file, or require them from a file required from a file required from a module.js file, etc.
- CJS/AMD modules right now, ES6 (modules and syntax) coming next.

**For app code:**
- `module.js` files are entry points.
- All other js files must be required in module.js files or other files or they'll be completely ignored (for now, definitely won't stay like this).
- No way (for now) to specify npm dependencies for app code since there's no `package.js` for app code, but this is easy to work around: just add the needed dependencies to a local package that depends on `rocket:module`, and use `Npm.depends` in that package to define npm dependencies.

**Note:**

Meteor currently only allows a single build plugin to handle a given file extension. `rocket:module` handles `.js` files, so this means you can't use other packages that provide build plugins for `.js` files (like Meteor's new `ecmascript` package). But no worries, the `ecmascript` packages serves to provide the latest ES features through Babel, which `rocket:module` will do anyways. People who use the coffeescript or typescript plugins would have to stop using those plugins for `rocket:module` when `rocket:module` supports those, same for css files, etc. Basically, `rocket:module` will be the single build plugin for all the files it handles. @glasser [mentioned](https://github.com/meteor/meteor/commit/f7ee0ba38507d1cca8ff6c1f8112d6e3f9835883#commitcomment-12310720) that the single-plugin-per-filetype rule might possibly be relaxed in the future.

**Comment by trusktr** [comment]
I forgot to mention, this currently only works with the `devel` branch of Meteor.

**Comment by trusktr** [comment]
@jantimon @cbioley Nevermind what I said about having to clone Meteor and checking out the `devel` branch. You can just run

``` sh
meteor --release PLUGINS-PREVIEW@1
```

to use the preview version of Meteor that has the new Plugin API. Still gotta clone rocket:module into `<your_app>/packages/module` though.

**Comment by trusktr** [comment]
@carrot93 Thanks for forking `rocket:module`. (: It is usable now. See above for some basic usage instructions.

**Comment by cyr-l** [comment]
Yay, congrats Joe!

I'm on holiday for two weeks starting today and I really need to try not be in front of the computer too often.

I'm looking forward to testing the plugin though.

Thanks again for your work and for the extensive info you gave us.

**Comment by trusktr** [comment]
@cbioley My pleasure! (: Two weeks should be plenty of time to work out the kinks that I'm discovering from publishing on Atmosphere. Some tiny details aren't quite the same with published packages compared to locally-installed packages (I developed rocket:module locally most of the time, then published today only to discover an error with the published version, which means that I have to publish new versions onto Atmosphere just to test out how published packages work, unfortunately).

**Comment by cyr-l** [comment]
Like having to use something like [meteor-files-helpers](https://github.com/Sanjo/meteor-meteor-files-helpers)? ;)

**Comment by trusktr** [comment]
@cbioley `rocket:module` is already using @sanjo's meteor-files-helpers. :)

**Comment by cyr-l** [comment]
In my face! ^^

**Comment by trusktr** [comment]
Hey guys, the [example app](https://github.com/meteor-rocket/module-example-app) is up and running. It's not finished yet, but the README should give you a good idea of how to start using `rocket:module`.
